import 'package:hive/hive.dart';

part 'contact.g.dart'; // This file is generated by Hive for type adapters.

@HiveType(typeId: 0) // Assign a unique typeId for this model
class Contact extends HiveObject {
  @HiveField(0)
  final String name;

  @HiveField(1)
  final String phone;

  Contact({required this.name, required this.phone});
}
